### ISSUE TITLE
Refactoring Value objects

### ISSUE THREAD

**Issue by elias480** [nmanero/ddd-crud#5]
Lo comentado en el hilo de correo con @nmanero y @sergiogragera.

Creo esta issue para renombrar los value object por domain y extraer  las propiedades en value objects reutilizables.

**Comment by nmanero** [comment]
Perfecto, te la he asignado @elias480

**Comment by nmanero** [comment]
En la PR acuerdate de poner #5 y así se puede conseguir cerrar esta issue al hacer el merge

**Comment by elias480** [comment]
Genial, en un rato lo apaño, gracias

**Comment by sergiogragera** [comment]
Sé que con un commit poniendo "fix #5..." se cerraba automáticamente la
issue. El problema es que conventionalcommits.org en principio solo
permitiría algo como "fix(#5): blah blah" y creo que lo realmente correcto
sería "fix: blah blah [#5]" pero no sé cómo se comportará con la issue. Lo
digo porque yo estoy con temas de hooks y si detectáis problemas con esto
me molaría ir adaptando el script.

Saludos.

**Comment by nmanero** [comment]
Yo prefiero fix(#5): asi todos los issues están al principio

**Comment by elias480** [comment]
Probaré a ponerlo como dices tú Nico, pero no sé si se podrá con los hooks que hay actualmente.

**Comment by nmanero** [comment]
Let's make a PR only with the changes in value objects and let's leave the datamappers... for other PRs.
